# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v2
    - name: Run client linters checks
      run: 
        npm ci
        npm run lint
